### PR TITLE
Add an example notebook for model-registry and Seldon integration

### PR DESCRIPTION
**Pull request by Lothiraldan**

### CODE REVIEW

**Comment by dsblank** [comment]
Suggestion:

Change:
```
!pip install -r requirements.txt
```
to:
```
%pip install -r requirements.txt
```
as that will ensure that the correct version of python is used.

**Comment by dsblank** [comment]
Bug:

This:
```
%pip install -r requirements.txt
```
should be:
```
%pip install -r ../../requirements.txt
```

**Comment by dsblank** [comment]
More suggestions:

* Add `xgboost` to requirements.txt
* Really bad security to put API_KEY in notebook, which is why we need comet.init()
* Change "for more informations." to "for more information."
* Why not register the model through the API? Maybe mention that possibility?
* experiment.workspace is None, if not named I believe which makes $WORKSPACE fail
* "wrapt" -> "wrapped"

**Comment by dsblank** [comment]
* do you need the typing stuff? it makes the example harder to follow

Can we replace this with python?
```
%%bash -s "{experiment.workspace}" "{API_KEY}"
export WORKSPACE="$1"
export REGISTRY_MODEL_NAME="xgboost-model-boston"
export REGISTRY_MODEL_VERSION="1.2.2"

env COMET_API_KEY="$2" python download_model.py --workspace "$WORKSPACE" --registry_name "$REGISTRY_MODEL_NAME" --model_version "$REGISTRY_MODEL_VERSION"
```

**Comment by Lothiraldan** [comment]
> More suggestions:
> 
>     * Add `xgboost` to requirements.txt
> 
>     * Really bad security to put API_KEY in notebook, which is why we need comet.init()
> 
>     * Change "for more informations." to "for more information."
>
>     * "wrapt" -> "wrapped"

Done

> 
>     * Why not register the model through the API? Maybe mention that possibility?

Do you have an example of such code? I think it might be cumbersome because you need to check if a registry model exists, if it doesn't, create it. Then compute the "next" version and register it.
> 
>     * experiment.workspace is None, if not named I believe which makes $WORKSPACE fail

Right, I got it defined in a config file, I will check how to get that value reliably.



> Can we replace this with python?
> 
> ```
> %%bash -s "{experiment.workspace}" "{API_KEY}"
> export WORKSPACE="$1"
> export REGISTRY_MODEL_NAME="xgboost-model-boston"
> export REGISTRY_MODEL_VERSION="1.2.2"
> 
> env COMET_API_KEY="$2" python download_model.py --workspace "$WORKSPACE" --registry_name "$REGISTRY_MODEL_NAME" --model_version "$REGISTRY_MODEL_VERSION"
> ```

Theoretically we could but we want to show the usage of `comet download_model` as it will be required outside of a notebook.

**Comment by dsblank** [comment]
You can register a model with:

```python
from comet_ml import API

api = API()

experiment = api.get("workspace-name/project-name/experiment-name")
experiment.register_model("MNIST CNN")
```

More here: 

* https://www.comet.ml/docs/user-interface/models/#2-register-a-model
* https://www.comet.ml/docs/python-sdk/APIExperiment/index.html#apiexperimentregister_model

**Comment by dsblank** [comment]
> I think it might be cumbersome because you need to check if a registry model exists, if it doesn't, create it. Then compute the "next" version and register it.

Maybe we need a way to save with incremented model version number?

**Comment by Lothiraldan** [comment]
@dsblank Are we in a good state to merge that notebook in its curent state?

**Comment by dsblank** [comment]
Checking...

**Comment by dsblank** [comment]
Some questions/comments:

1. Do we still need the custom download_model code?
2. The Register the model instructions could use some more text:

```
Click on the `+ Register` link, then click `Register new model`, and click the registered model to exactly the name and model number. Also, note the name of your workspace (usually your comet id). 
```
3. Did you mean to overwrite the requirements.txt file with this new version?

**Pull request merged**
